### ISSUE TITLE
MyAlerts integration

### ISSUE THREAD

**Issue by keithpickering** [Sama34/OUGC-Awards#15]
I see that there's some MyAlerts integration within this plugin, but it doesn't seem to actually do anything. I've uncommented the hidden code so the option appears in the OUGC Awards settings. Did you run into any trouble getting this integration working? What needs to be done in order to make it functional? Thanks.

**Comment by Sama34** [comment]
If I recall correctly the code was for the old version of MyAlers, so it shouldn't work at all.
