### ISSUE TITLE
Add stats to forum stats page - user with the most awards etc.

### ISSUE THREAD

**Issue by Eldenroot** [Sama34/OUGC-Awards#17]
Add stats to forum stats page - user with the most awards etc.

**Comment by Sama34** [comment]
This is how it looks.
![clipboard01](https://cloud.githubusercontent.com/assets/1786584/17804510/d4237184-65b0-11e6-8850-3165973d4ca2.jpg)

**Comment by Cu8eR** [comment]
GJ
