### ISSUE TITLE
Integrate with group promotions

### ISSUE THREAD

**Issue by Sama34** [Sama34/OUGC-Awards#18]
Two new fields should be added to the group promotion rules to give/remove an award upon promoting an user.

**Comment by Cu8eR** [comment]
+1

**Comment by Sama34** [comment]
I will delay this, because I'm adding a new requested feature by a client that resembles a little this and I'm unsure how this will be useful.

The only way I will probably add this is if it is a "Needs X award to be promoted." but I could as well add that setting to the new feature instead.

**Comment by Cu8eR** [comment]
@Sama34 - any news? At least release a minor version?

**Comment by Sama34** [comment]
I think something was coded but I need to verify what happened with the client who requested this.
