### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by ks129** [Sama34/OUGC-Awards#28]
I uploaded files to server, but now plugins page is blank.

**Comment by Sama34** [comment]
I think this is related to #30. Please use revised package and reply only if not.

**Comment by SoftwareN00b** [comment]
Issue still persists, I attempted to use the past 3 releases with various commits and plugins page is still blank.

**Comment by Sama34** [comment]
This issue is a duplicate, if you follow the issue mentioned in my last comment you will find the original issue with its patch.
