### ISSUE TITLE
Add support for FontAwesome icons

### ISSUE THREAD

**Issue by Eldenroot** [Sama34/OUGC-Awards#32]
I would like to see a support for FontAwesome icons and CSS. How to do that? Maybe the easiest way would be to add a posibility custom CSS for every award (we would need to have an unique ID for every award and use it as a css class).

This makes sense -> more CSS, less images. FontAwesome is really popular.

**Comment by Sick1G** [comment]
Yes, this would be awesome.

One column for HTML input where you can put font awesome for example like `<i class="fa fa-something"></i> `
Then style it normally with CSS.

**Comment by Eldenroot** [comment]
I think we just need only add an unique css class for every award and style it with :before attribute. Nothing difficult :)

**Comment by Sama34** [comment]
Hi Eldenroot. I replied to your post in the community.
https://community.mybb.com/thread-116640-post-1321498.html#pid1321498

This is already possible by default, you just need to edit the template to meet your requirements and include your library manually in `headerinclude`.

I use the Semantic UI library so by default the template code reflects that. But not library is added by default and it will never do.

Please confirm this meets your suggestion.

**Comment by Eldenroot** [comment]
@Sama34 - I do not wanna to include FontAwesome library into your OUGC awards plugin, I just want to add a support for that so everyone can use that feature if will be needed. 

Please can you send me a working example of CSS code you use for your icon library, I am unableto make it working with FontAwesome, maybe I make something wrong :( thank you!

**Comment by Sick1G** [comment]
@eldenroot trust me html approach is way better because maybe you eant a special border or shadows on some icon, not all fonts are same size and so on. I have a private version of omarG awards system where there is a HTML field and possibilities are limitless.

**Comment by Sama34** [comment]
@Eldenroot, Try following the steps provided in the [FAQs section of the official page](https://omarg.me/module?public/faqs&filtertf_plugins_plugin=1).

You can check a temporal example [here](https://mybb-es.com/awards.php)
![image](https://user-images.githubusercontent.com/1786584/50636450-f2da6780-0f0a-11e9-8e2e-7c2c20400f8d.png)
![image](https://user-images.githubusercontent.com/1786584/50636465-ff5ec000-0f0a-11e9-958f-f852f4b2fcc9.png)
![image](https://user-images.githubusercontent.com/1786584/50636478-11406300-0f0b-11e9-9bbf-82d5be2df69a.png)

Only thing is that the library should be included in `headerinclude` and not inside the template as I did for this example.

@Sick1G, OUGC Awards supports for custom templates on a per award basis and you can also use a different template by category, I have documented that in the FAQs section as well if you are interested.

**Comment by Eldenroot** [comment]
@Sama34 - thank you for a tutorial! I will try later today and let you know the result :)
