### ISSUE TITLE
OUGC Images Repeating

### ISSUE THREAD

**Issue by Drunken-Cheetah** [Sama34/OUGC-Awards#55]
Using latest mybb version and a github theme from mybb community,

Since I haven't really been helped on the forums, I thort i'd post here.

I have installed OUGC awards plugin, but for some reason when I use {bburl}/images/awards/discord.png is just repeats in the post bit.

https://community.mybb.com/attachment.php?thumbnail=41748
I've only given it to myself, once not 3 times and I have scoured the forums for someone else who has this kind of issue but haven't found anything

The postbit only has  {$post['ougc_awards']} once, 
this has really got me dumbfounded, as I cant use the plugin but nobody seem's to want to help.

Hoping someone here can help, thanks

**Comment by suryadewa** [comment]
same as me.. OUGC Awards duplication in post bit

**Comment by Skryptific** [comment]
Check this out, done a pull request: https://github.com/Sama34/OUGC-Awards/pull/57/files

**Comment by Sama34** [comment]
Please see #43
