### ISSUE TITLE
Call to undefined function `create_function()`

### ISSUE THREAD

**Issue by tedem** [Sama34/OUGC-Awards#73]
The create_function() function in PHP is causing an error because it has been completely removed with PHP 8.0. Instead, anonymous functions can be used.

Original thread: https://community.mybb.com/thread-237734-post-1383879.html

**Comment by Sama34** [comment]
`create_function()` is already removed in the `develop` branch, I will eventually release it when I got the time and start updating my plugins for PHP 8, thanks for your report.

**Comment by tedem** [comment]
You're welcome, happy coding!
